CREATE TABLE IF NOT EXISTS system_param
(
  id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
	paramName VARCHAR(50) NOT NULL COMMENT '参数名称',
	paramValue VARCHAR(255) NOT NULL COMMENT '参数值',
	description VARCHAR(255) NULL DEFAULT NULL COMMENT '描述',
	createTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	operatorId BIGINT(20) NULL DEFAULT NULL COMMENT '操作人id',
	operatorName VARCHAR(30) NULL DEFAULT NULL COMMENT '操作人账号',
	opVersion VARCHAR(30) NULL DEFAULT NULL COMMENT '版本号',
	PRIMARY KEY (id)
)comment '系统参数表';